@startuml

package javaFX {
  class TextField {
    -text : String
    +TextField()
    +TextField(String)
    +setText(String)
    +setOnAction(EventHandler)
  }

  class CheckBox {
    -isChecked : boolean

    +CheckBox()
    +CheckBox(String)
    +setSelected(boolean)
    +fire()
    +isSelected()
    +setOnAction(EventHandler)
  }

  class Label {
    -text : String
    +Label(String text)
    +getText() : String
    +setText(String)
  }

  class Button {
    +Button(String)
    +setOnAction(EventHandler)
  }

  class BorderPane {
    BorderPane()
    setTop(Node)
    setCenter(Node)
    setLeft(Node)
    setRight(Node)
    setBottom(Node)
  }
}

package java {
  interface Iterable<T> {
    iterator() : Iterator<T>
  }
}

package MVC {
  interface Model {
    addObservator(Observator)
    deleteObservator(Observator)
    updateObservator()
  }

  interface Observator {
    update(Model)
  }
}

package Collaborator {
  class CollaboratorList implements java.Iterable {
    +addCollaborator(String)
    +deleteCollaborator(String)
  }

  CollaboratorList "1" <-- "1" javaFX.TextField : newCollaborator
  CollaboratorList o-- javaFX.TextField : collaborators
}

package Task {

  class Task {
    -taskId : int
    -{static} maxId : int
    -{static} allTasks : list<Task>
    +Task() //taskId = ++maxId && add it to "allTask"
    +Task(String) //taskId = ++maxId && add it to "allTask"
    +Task(String, String) //taskId = ++maxId && add it to "allTask"
    +{static}getTaskById(int) : Task

    +addSubTask(Task)
    +deleteSubTask(Task)
    +getSubTasks()

    +addDependencie(Task)
    +deleteDependencie(Task)
    +getDependencies()

    +[getter]()
  }

  class DependencieList implements java.Iterable{
    +addDependencie(int)
    +deleteDependencie(int)
    +isEmpty()
  }

  class TaskList implements java.Iterable {
    +addTask(Task)
    +deleteTask(Task)
    +isEmpty()

    +[getter]()
  }

  Task "1" <-- "1" DependencieList : dependencies
  Task "*" <-up- "1" Task : parentTask
  Task "*" <-- "1" TaskList : parentTaskList
  Task o-- Task : subTasks
  Task "*" <-- "1" Collaborator.CollaboratorList : collaborators
  Task "1" <-- "1" javaFX.TextField : name
  Task "1" <-- "1" javaFX.TextField : description
  Task "1" <-- "1" javaFX.CheckBox : archive

  TaskList o-- Task : tasks
  TaskList "1" <-- "1" javaFX.TextField : name
  TaskList "1" <-- "1" javaFX.CheckBox : archive
  TaskList "1" <-- "1" javaFX.Button : addTask

  DependencieList o-- javaFX.TextField : dependenciesId
}

package App {
  class Treulo implements MVC.Model{
    -displayArchive : boolean
    -displayMode : String
    +loadFile(String fileName)
    +saveAsFile(String fileName)
    +exportAsImage(String fileName)
    +[getter]()
  }

  Treulo "1" <-- "*" MVC.Observator : observators
  Treulo "1" <-- "*" Task.TaskList : Tasks
  Treulo "1" <-- "1" javaFX.Button : addTaskList

  class AppView extends javaFX.BorderPane implements MVC.Observator {
    "//update use DisplayFactory.getDisplayFactory()\nto display the tasks"
  }
}


package Display {
  interface Display {
    +getDisplay() : Node
    +getTaskDisplay(Task, Node) : Node //Called recursivly to display tasks
  }

  class DeskDisplay implements Display {
    +DeskDisplay(ArrayList<TaskList>)
    -getListDisplay(TaskList) : Node
  }
  DeskDisplay "*" <-- "*" Task.TaskList : taskLists

  class ListDisplay implements Display {
    +ListDisplay(ArrayList<TaskList>)
    -getListDisplay(TaskList) : Node
  }
  ListDisplay "*" <-- "*" Task.TaskList : taskLists

  class GanttDisplay implements Display {
    +GanttDisplay(Task finalTask)
  }
  GanttDisplay "*" <-- "1" Task.Task : finalTask

  package DisplayFactory {
    abstract class DisplayFactory {
      +{abstract} createDisplay() : Display
      +{static} getDisplayFactory(Treulo, String) : DisplayFactory
    }

    class DeskDisplayFactory extends DisplayFactory{
      DeskDisplayFactory(Treulo)
    }
    DeskDisplayFactory "*" <-- "1" Treulo : model

    class ListDisplayFactory extends DisplayFactory{
      ListDisplayFactory(Treulo)
    }
    ListDisplayFactory "*" <-- "1" Treulo : model

    class GanttDisplayFactory extends DisplayFactory{
      GanttDisplayFactory(Treulo)
    }

    GanttDisplayFactory "*" <-- "1" Treulo : model
  }
}

package Controler {
  class EditTaskControl {
    EditTaskControl(Treulo, Task)
    Handle(ActionEvent)
  }
  EditTaskControl "*" <-- "1" Task.Task : task
  EditTaskControl "*" <-- "1" Treulo : model

  class AddTaskControl {
    AddTaskControl(Treulo, TaskList)
    Handle(ActionEvent)
  }
  AddTaskControl "*" <-- "1" Task.TaskList : taskList
  AddTaskControl "*" <-- "1" Treulo : model

  class DeleteTaskControl {
    DeleteTaskControl(Treulo)
    Handle(ActionEvent)
  }
  DeleteTaskControl "*" <-- "1" Treulo : model

  class EditTaskListControl {
    EditTaskListControl(Treulo, TaskList)
    Handle(ActionEvent)
  }
  EditTaskListControl "*" <-- "1" Task.TaskList : taskList
  EditTaskListControl "*" <-- "1" Treulo : model

  class AddTaskListControl {
    AddTaskListControl(Treulo)
    Handle(ActionEvent)
  }
  AddTaskListControl "*" <-- "1" Treulo : model

  class DeleteTaskListControl {
    DeleteTaskListControl(Treulo)
    Handle(ActionEvent)
  }
  DeleteTaskListControl "*" <-- "1" Treulo : model

  class EditCollaboratorListControl {
    EditCollaboratorListControl(Treulo, CollaboratorList)
    Handle(ActionEvent)
  }
  EditCollaboratorListControl "*" <-- "1" Collaborator.CollaboratorList : collaboratorList
  EditCollaboratorListControl "*" <-- "1" Treulo : model

  class EditDependencieListControl {
    EditDependencieList(Treulo, DependencieList)
    Handle(ActionEvent)
  }
  EditDependencieListControl "*" <-- "1" Task.DependencieList : dependencieList
  EditDependencieListControl "*" <-- "1" Treulo : model

  class OpenFileControl {
    OpenFileControl(Treulo)
    Handle(ActionEvent)
  }
  OpenFileControl "*" <-- "1" Treulo : model

  class SaveFileControl {
    SaveFileControl(Treulo)
    Handle(ActionEvent)
  }
  SaveFileControl "*" <-- "1" Treulo : model

  class ExportImageControl {
    ExportImageControl(Treulo)
    Handle(ActionEvent)
  }
  ExportImageControl "*" <-- "1" Treulo : model

  class TaskDragControl {
    TaskDragControl(Treulo)
    Handle(DragEvent )
  }
  note right of TaskDragControl
    I don't know how to implement that
  end note

  TaskDragControl "*" <-- "1" Treulo : model

  class ToggleArchiveControl {
    ToggleArchiveControl(Treulo)
    Handle(ActionEvent)
  }
  ToggleArchiveControl "*" <-- "1" Treulo : model

  class ChangeDisplayControl {
    ChangeDisplayControl(Treulo)
    Handle(ActionEvent)
  }
  ChangeDisplayControl "*" <-- "1" Treulo : model
}



@enduml