@startuml

interface Model {
    addObservator(Observator)
    deleteObservator(Observator)
    updateObservator()
}

class Treulo implements Model{
    -displayArchive : boolean
    -displayMode : String
    -isDisplayingSubTask : boolean
    -loadFile(String fileName)
    -saveAsFile(String fileName)
    -exportAsImage(String fileName)
    +[getter]()
}

Treulo "1" <-- "*" Observator : observators
Treulo "1" <-- "1" Board : board
Treulo "*" <-- "1" Task : displayedTask \n//used for subtask, gantt & subtask gantt
Treulo "*" <-- "1" Task : focusedTask \n//used for big display

interface Observator {
    update(Model)
}

class AppView extends "BorderPane(javafx)" implements Observator{

}

AppView "1" <-- "1" DisplayFactory : displayFactory

note "Update display the entire app\nstrategy used for display type" as N1
AppView <- N1

class DisplayFactory {
    +DisplayFactory(Treulo)
    +generateDisplay(String displayMode) : Display
    +generateSubTaskDisplay(String displayMode, Task task) : Display
}

DisplayFactory "1" <-- "1" Treulo : model

interface Display {
    +getDisplay(Task focusedTask) : Node
}

class DeskDisplay implements Display {
    +DeskDisplay(ArrayList<TaskContainer>)
    -getContainerDisplay(TaskContainer) : Node
}
DeskDisplay "*" <-- "*" TaskContainer : taskContainers

class ListDisplay implements Display {
    +ListDisplay(ArrayList<TaskContainer>)
    -getContainerDisplay(TaskContainer) : Node
}
ListDisplay "*" <-- "*" TaskContainer : taskContainers

class GanttDisplay implements Display {
    +GanttDisplay(Task finalTask)
}
GanttDisplay "*" <-- "1" Task : finalTask

class TaskContainer implements "Iterable<Task>(java)"{
    -name : String
    +addTask(Task)
    +deleteTask(Task)
    +isEmpty()

    +[getter]()
}

TaskContainer "1" <-- "*" Task : tasks
note on link : linked list pour \nmodification rapide de l'ordre

abstract class Task {
    -name : String
    -description : String
    -isArchived : boolean
    -isFocused : boolean

    +addDependencie(Task)
    +deleteDependencie(Task)
    +addWorker(Worker)
    +deleteWorker(Worker)

    {abstract}+toNode() : Node //display of a single node, depending on isFocused

    +[getter]()
}

Task "*" <-- "*" Task : dependencies
Task "*" <-- "*" Worker : assignedWorker

class TaskAlone extends Task {

}

class TaskWithSubTask extends Task {

}

TaskWithSubTask "1" <-- "1" Board : subTask

class Worker {
    -name
}

class Board implements "Iterable<TaskContainer>(java)"{
    +name : String

    +addContainer(TaskContainer)
    +deleteContainer(TaskContainer)
    +isEmpty()

    +[getter]()
}
Board "1" <-- "*" TaskContainer : containers
note on link : linked list pour \nmodification rapide de l'ordre

class TaskDragControl {
    TaskDragControl(Treulo)
    Handle(DragEvent )
}
TaskDragControl "*" <-- "1" Treulo : model

class AddTaskControl {
    AddTaskControl(Treulo)
    Handle(ActionEvent )
}
AddTaskControl "*" <-- "1" Treulo : model

class EditTaskControl {
    EditTaskControl(Treulo)
    Handle(ActionEvent)
}
EditTaskControl "*" <-- "1" Treulo : model

class DeleteTaskControl {
    DeleteTaskControl(Treulo)
    Handle(ActionEvent )
}
DeleteTaskControl "*" <-- "1" Treulo : model

class ChangeDisplayControl {
    ChangeDisplayControl(Treulo)
    Handle(ActionEvent)
}
ChangeDisplayControl "*" <-- "1" Treulo : model

class SaveFileControl {
    SaveFileControl(Treulo)
    Handle(ActionEvent )
}
SaveFileControl "*" <-- "1" Treulo : model

class LoadFileControl {
    LoadFileControl(Treulo)
    Handle(ActionEvent )
}
LoadFileControl "*" <-- "1" Treulo : model

class ExportImageControl {
    ExportImageControl(Treulo)
    Handle(ActionEvent )
}
ExportImageControl "*" <-- "1" Treulo : model

class ToggleArchiveTaskControl {
    ToggleArchiveTaskControl(Treulo)
    Handle(ActionEvent )
}
ToggleArchiveTaskControl "*" <-- "1" Treulo : model

class AddContainerControl {
    AddContainerControl(Treulo)
    Handle(ActionEvent )
}
AddContainerControl "*" <-- "1" Treulo : model

class DeleteContainerControl {
    DeleteContainerControl(Treulo)
    Handle(ActionEvent )
}
DeleteContainerControl "*" <-- "1" Treulo : model

class UpdateContainerControl {
    UpdateContainerControl(Treulo)
    Handle(ActionEvent )
}
UpdateContainerControl "*" <-- "1" Treulo : model

@enduml