@startuml

Main -> Affichage : getDisplay()
activate Affichage

loop TaskList
Affichage -> TaskList : isArchived()
activate TaskList
Affichage <-- TaskList : archivé ?
deactivate TaskList

alt non archivé ou archive affichée
    Affichage -> TaskList : getInfo()
    activate TaskList
    Affichage <-- TaskList : infos
    deactivate TaskList

    Affichage -> Affichage : généré affichage liste

    Affichage -> TaskList : getTasks()
    activate TaskList
    Affichage <-- TaskList : tasks
    deactivate TaskList

    Affichage -> task : isArchived()
    activate task
    Affichage <-- task : archivé ?
    deactivate task

    alt non archivé ou archive affichée
        Affichage -> task : getInfo()
        activate task
        Affichage <-- task : infos
        deactivate task
        Affichage -> Affichage : généré affichage tâche
    end
end

end loop

Main <-- Affichage : affichage

@enduml