@startuml

activate AppView

AppView -> GanttDisplay : getDisplay()
activate GanttDisplay

    loop Taskslist
    GanttDisplay -> Taskslist : info requests
    activate Taskslist
    GanttDisplay <-- Taskslist : infos
    deactivate Taskslist

    GanttDisplay -> GanttDisplay : update of the display

    GanttDisplay -> Taskslist : getTasks()
    activate Taskslist
    GanttDisplay <-- GanttDisplay : tasks
    deactivate Taskslist

        loop Tasks
        GanttDisplay -> TreuloTask : info requests
        activate TreuloTask
        GanttDisplay <-- TreuloTask : infos
        deactivate TreuloTask

        GanttDisplay -> GanttDisplay : update of the display
        end loop
    end loop


AppView <-- GanttDisplay : Node
deactivate GanttDisplay



@enduml