@startuml

activate AppView

AppView -> DeskDisplay : getDisplay()
activate DeskDisplay

    loop Taskslist
    DeskDisplay -> Taskslist : info requests
    activate Taskslist
    DeskDisplay <-- Taskslist : infos
    deactivate Taskslist

    DeskDisplay -> DeskDisplay : update of the display

    DeskDisplay -> Taskslist : getTasks()
    activate Taskslist
    DeskDisplay <-- Taskslist : tasks
    deactivate Taskslist

        loop Tasks
        DeskDisplay -> TreuloTask : info requests
        activate TreuloTask
        DeskDisplay <-- TreuloTask : infos
        deactivate TreuloTask

        DeskDisplay -> DeskDisplay : update of the display
        end loop
    end loop


AppView <-- DeskDisplay : Node
deactivate DeskDisplay



@enduml